### ISSUE TITLE
Please add AI-related project topics

### ISSUE THREAD

**Issue by leebrian** [CDCgov/NLPWorkbench#3]
In OMB's [Implementation Guidance to Federal Agencies Regarding Enterprise Data and Source
Code Inventories](https://code.gov/assets/data/ai_inventory-guidance.pdf) they established a set of AI/ML-related keywords and tags for government work.

I think the cool work in this project is AI-related, would you please update the GitHub project properties to add these keywords to your project topics? Specifically, I think you should add "“usg-artificial-intelligence”.

Once you update your project settings, these changes will be automatically picked up by CDC's metadata scraper and included in the [code.json](https://www.cdc.gov/code.json) file used by GSA to index and include projects in the federal code catalog.

For help on how to update your project, please check out [Github's documentation](https://help.github.com/en/articles/classifying-your-repository-with-topics) or just send me an email.

**Comment by mscaldas2012** [comment]
Metadata Added!
